---
title: "General Approach"
author: "Yuanxi He"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
### Cleanup:
rm( list=ls() )

### Libraries:
library(quantmod)
library(ggplot2)
library(tseries)
library(moments)
library(sandwich)
library(lmtest)
library(stats)
```

## Initial setting
```{r, warning=FALSE, message=FALSE}
## Importing data:
getSymbols(Symbols = "^IXIC", auto_assign = TRUE, from = "1971-02-08")
df<-as.data.frame(IXIC)
rm(IXIC)

save(df, file = "./data/nasdaq.RData")

## Constructing variables:
dates <- as.Date(as.character(rownames(df)),'%Y-%m-%d')
T <- nrow(df)
price <- df[,6]
returns <- diff(log(price))*100
```

### Growth plots:
```{r, warning=FALSE, message=FALSE, error=FALSE}
ggplot() +
  geom_line(mapping = aes(x = dates, y = price),col='tomato')+
  scale_x_date(date_breaks = "5 year", date_labels = "%Y %b %d")+
  ylab("NASDAQ Stock price")+
  xlab("Dates")+
  theme_light()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot() +
  geom_line(mapping = aes(x = dates, y = log(price)),col='tomato')+
  scale_x_date(date_breaks = "5 year", date_labels = "%Y %b %d")+
  ylab("NASDAQ Stock price with log")+
  xlab("Dates")+
  theme_light()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

### Augmented Dickey-Fuller tests:
adf.test(price)
adf.test(log(price))
adf.test(returns)
```

## Standardizing returns:
```{r, warning=FALSE, message=FALSE, error=FALSE}
ret_sq <- returns^2
ret_abs <- abs(returns)

ret <- cbind.data.frame(dates[2:T],returns,ret_abs,ret_sq)

colnames(ret)<-c("dates","returns","abs_returns","sq_returns")

save(ret, file = "data/returns.RData")
```

## Stationarity-ADF test:
```{r, warning=FALSE, message=FALSE, error=FALSE}
ggplot() +
  geom_line(mapping = aes(x = dates[2:T], y = returns),col='tomato')+
  geom_hline(yintercept=0, color = "darkblue")+
  scale_x_date(date_breaks = "5 year", date_labels = "%Y %b %d")+
  ylab("NASDAQ returns")+
  xlab("Dates")+
  theme_light()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

### Augmented Dickey-Fuller tests:
adf.test(returns)
adf.test(ret_sq)
adf.test(ret_abs)
```

## Distributional Properties-JB test:
```{r, warning=FALSE, message=FALSE, error=FALSE}
kernel <- density(returns)

par(mar=c(2,2,0.5,0.5), mfrow=c(2,1))

plot( kernel , main='', xlim=c(-10,10) )
polygon( kernel , col="tomato" , border='darkred' )
lines( seq(-10,10,0.1) , dnorm( seq(-10,10,0.1) , mean(returns) , sd(returns) ) , col='darkblue' ,lwd=4)

qqnorm(returns,col='tomato',main='')
qqline(returns,lwd=2,lty=3)

### Jarque-Bera tests:
jarque.test(returns)
jarque.test(ret_sq)
jarque.test(ret_abs)
```

## Basic Statistics Summary:
```{r, warning=FALSE, message=FALSE, error=FALSE, include=FALSE}
descr <- as.matrix(round(c(min(returns),mean(returns),median(returns), max(returns),sd(returns), sqrt(252)*sd(returns), skewness(returns), kurtosis(returns)),3))

descr<-cbind.data.frame(descr)
colnames(descr)<-c("Returns")
rownames(descr)<- list('Minimum return (2020-03-16)','Average return','Median Return','Maximum return (2001-01-03)','Daily volatility','Annualized volatility','Skewness','Kurtosis')

knitr::kable(descr)
```

## ACF:
```{r, warning=FALSE, message=FALSE, error=FALSE}
par(mar=c(2,2,0.5,0.5), mfrow=c(2,1))

ret.acf <- acf(returns, lwd=5, col='tomato', lag.max = 50) ## ACF for returns
legend('topright',c('ACF of returns'),cex=0.8,lwd=2, col='tomato')

ret.pacf <- pacf(returns , ylim=c(-0.05,0.5), lwd=5, col='tomato', lag.max = 50) ## PACF for returns
legend('topright',c('PACF of returns'),cex=0.8,lwd=2, col='tomato')

#############

par(mar=c(2,2,0.5,0.5), mfrow=c(2,2))
ret_sq.acf <- acf(ret_sq, lwd=5, col='tomato', lag.max = 50) ## ACF for squared returns
legend('topright',c('ACF of squared returns'),cex=0.8,lwd=2, col='tomato')

ret_sq.pacf <- pacf(ret_sq, lwd=5, col='tomato', lag.max = 50) ## PACF for squared returns
legend('topright',c('PACF of squared returns'),cex=0.8,lwd=2, col='tomato')

ret_abs.acf <- acf(ret_abs, lwd=5, col='tomato', lag.max = 50) ## ACF for absolute returns
legend('topright',c('ACF of absolute returns'),cex=0.8,lwd=2, col='tomato')

ret_abs.pacf <- pacf(ret_abs, lwd=5, col='tomato', lag.max = 50) ## PACF for absolute returns
legend('topright',c('PACF of absolute returns'),cex=0.8,lwd=2, col='tomato')

#############
print(ret.acf)
print(ret.pacf)

### Box-Ljung tests:
Box.test(returns, lag=50, type="Ljung-Box")
Box.test(ret_sq, lag=50, type="Ljung-Box")
Box.test(ret_abs, lag=50, type="Ljung-Box")
```

