---
title: "K-Means Clustering"
author: "Yuanxi He"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Importing all packages
```{r, include=FALSE}
### Cleanup:
rm( list=ls() )

### Libraries:
library(ggplot2)
library(tseries)
library(moments)
library(sandwich)
library(lmtest)
library(stats)
library(ClusterR)
library(cluster)
library(dplyr)
library(plotly)
library(ggpubr)
library(factoextra)
library(NbClust)
library("scatterplot3d")
```

## Initial setting
```{r setup, warning=FALSE, message=FALSE}
## Importing data:
getSymbols(Symbols = "^STOXX50E", auto_assign = TRUE, from = "1971-02-08")
df<-as.data.frame(na.omit(STOXX50E))
rm(STOXX50E)

save(df, file = "./data/eurostoxx50.RData")
load("./data/eurostoxx50.RData")

## Constructing variables:
dates <- as.Date(as.character(rownames(df)),'%Y-%m-%d')
T <- nrow(df)
price <- df[,6]
returns <- diff(log(price))*100
```

## Rolling: 
```{r}
### Month window:
rollapply(returns, FUN = mean, width = 20, by.column = TRUE)->m
rollapply(returns, FUN = sd, width = 20, by.column = TRUE)->std
rollapply(returns, FUN = skewness, width = 20, by.column = TRUE)->skew
rollapply(returns, FUN = kurtosis, width = 20, by.column = TRUE)->kurt

rollm<-na.omit(data.frame(dates = dates[21:T],
                  cbind(m,std,skew,kurt)))
rm(m,std,skew,kurt)

colMeans(rollm[,c(2:5)])
```

## Clustering (1 month):
```{r}
######### Month windows (m+std):
set.seed(111111111)
res41 <- kmeans(rollm[,c(2:3)], centers = 2, nstart = 25)
res41$centers
y_kmeans41 <- as.character(res41$cluster)

ggplot() +
  geom_point(data = rollm, mapping = aes(x = m, y = std, colour = y_kmeans41))+
  geom_point(mapping = aes_string(x = res41$centers[,1], y = res41$centers[,2]), color = "darkblue", size = 4, alpha=0.7)+
  ylab("Standard Deviation")+
  xlab('Mean')+
  scale_colour_brewer(palette = "Set2")+
  theme_light()+
  theme(legend.position="top")
  
######### Month windows (m+std+skew):
set.seed(11111111)
res42 <- kmeans(rollm[,c(2:4)], centers = 2, nstart = 25)
res42$centers
y_kmeans42 <- as.character(res42$cluster)

colors <- c("#66C2A5", "#FC8D62", "#8DA0CB")
colors <- colors[as.numeric(res42$cluster)]

scatterplot3d(rollm[,2:4], pch = 16, color=colors, grid=TRUE)

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = m, y = std, colour = y_kmeans42))+
  geom_point(mapping = aes_string(x = res42$centers[,1], y = res42$centers[,2]), 
               color = "darkblue", size = 4, alpha=0.7)+
  ylab("Standard Deviation")+
  xlab('Mean')+
  scale_colour_brewer(palette = "Set2")+
  theme_light()

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = std, y = skew, colour = y_kmeans42))+
  geom_point(mapping = aes_string(x = res42$centers[,2], y = res42$centers[,3]), 
               color = "darkblue", size = 4, alpha=0.7)+
  ylab("Skewness")+
  xlab('Standard Deviation')+
  scale_colour_brewer(palette = "Set2")+
  theme_light()

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = m, y = skew, colour = y_kmeans42))+
  geom_point(mapping = aes_string(x = res42$centers[,1], y = res42$centers[,3]), 
               color = "darkblue", size = 4, alpha=0.7)+
  ylab("Skewness")+
  xlab('Mean')+
  scale_colour_brewer(palette = "Set2")+
  theme_light()

######### Month windows (m+std+skew+kurt):
set.seed(11111)
res43 <- kmeans(rollm[,c(2:5)], centers = 2, nstart = 25)
res43$centers
y_kmeans43 <- as.character(res43$cluster)

colors <- c("#66C2A5", "#FC8D62", "#8DA0CB")
colors <- colors[as.numeric(res43$cluster)]

par(mfrow=c(2,2))
scatterplot3d(rollm[,c(2,3,4)], pch = 16, color=colors, grid=TRUE)
scatterplot3d(rollm[,c(2,3,5)], pch = 16, color=colors, grid=TRUE)
scatterplot3d(rollm[,c(2,4,5)], pch = 16, color=colors, grid=TRUE)
scatterplot3d(rollm[,c(3,4,5)], pch = 16, color=colors, grid=TRUE)

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = m, y = std, colour = y_kmeans43))+
  geom_point(mapping = aes_string(x = res43$centers[,1], y = res43$centers[,2]), 
               color = "darkblue", size = 4, alpha=0.7)+
  theme_light()

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = m, y = skew, colour = y_kmeans43))+
  geom_point(mapping = aes_string(x = res43$centers[,1], y = res43$centers[,3]), 
               color = "darkblue", size = 4, alpha=0.7)+
  theme_light()

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = m, y = kurt, colour = y_kmeans43))+
  geom_point(mapping = aes_string(x = res43$centers[,1], y = res43$centers[,4]), 
               color = "darkblue", size = 4, alpha=0.7)+
  theme_light()

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = std, y = skew, colour = y_kmeans43))+
  geom_point(mapping = aes_string(x = res43$centers[,2], y = res43$centers[,3]), 
               color = "darkblue", size = 4, alpha=0.7)+
  theme_light()

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = std, y = kurt, colour = y_kmeans43))+
  geom_point(mapping = aes_string(x = res43$centers[,2], y = res43$centers[,4]), 
               color = "darkblue", size = 4, alpha=0.7)+
  theme_light()

ggplot() +
  geom_point(data = as.data.frame(rollm), mapping = aes(x = skew, y = kurt, colour = y_kmeans43))+
  geom_point(mapping = aes_string(x = res43$centers[,3], y = res43$centers[,4]), 
               color = "darkblue", size = 4, alpha=0.7)+
  theme_light()
```

## Classify by clusters (monthly):
```{r}
dd_rm<-cbind(rollm,clust_1=y_kmeans41,clust_2=y_kmeans42,clust_3=y_kmeans43,price=df[,6][c(21:T)])
dd_rm<-dd_rm[,-c(2:5)]

ggplot(dd_rm, aes(x=dates,y=price, group=clust_1, color=clust_1))+
  geom_point(size=0.5)+
  geom_bar(aes(y=price, fill=clust_1),stat="identity")+  
  ylab("Euro Stoxx 50 price")+
  xlab("Dates")+
  scale_x_date(date_breaks = "1 year", date_labels = "%Y %b %d")+
  theme_light()+
  theme(
    axis.title=element_text(size=10,face="bold"),
    axis.text.x = element_text(angle=60, hjust=1),
    legend.position="none")+
  scale_colour_brewer(palette = "Set2")
```

## Strategy:
```{r}
### Monthly: 
buy=0
sell=0
profit=0
normal_profit=0

for (i in 1:dim(dd_rm)[1]) {   
    if (i==1) { 
      if (dd_rm$clust_1==1){
        buy<-as.numeric(dd_rm[i,5])
        }
    } 
    else if (dd_rm[i,2]==2 & dd_rm[i-1,2]==1) {
        sell<-as.numeric(sell+dd_rm[i,5])
    } 
    else if (dd_rm[i,2]==1 & dd_rm[i-1,2]==2) {
        buy<-as.numeric(buy+dd_rm[i,5])
    } 
    profit[i]<-as.vector(print(sell-buy))
    normal_profit[i]<-as.vector(print(dd_rm[i,5]-dd_rm[1,5]))
}

tail(profit, n=1)
tail(normal_profit, n=1)

buy=0
sell=0
profit=0
normal_profit=0

for (i in 1:dim(dd_rm)[1]) {   
    if (i==1) { 
      if (dd_rm$clust_1==2){
        buy<-as.numeric(dd_rm[i,5])
        }
    } 
    else if (dd_rm[i,2]==1 & dd_rm[i-1,2]==2) {
        sell<-as.numeric(sell+dd_rm[i,5])
    } 
    else if (dd_rm[i,2]==2 & dd_rm[i-1,2]==1) {
        buy<-as.numeric(buy+dd_rm[i,5])
    } 
    profit[i]<-as.vector(print(sell-buy))
    normal_profit[i]<-as.vector(print(dd_rm[i,5]-dd_rm[1,5]))
}

tail(profit, n=1)
tail(normal_profit, n=1)

jpeg("./fig/rm_profit_eurostoxx.jpg", units="in", width=7, height=7, res=300)
ggplot(dd_rm, aes(x=dates)) + 
  geom_point(aes(y = price, group=clust_1, color=clust_1), size=0.5) + 
  geom_bar(aes(y=profit, fill=clust_1),stat="identity")+  
  scale_fill_brewer(palette="Set2")+
  scale_colour_brewer(palette = "Set2")+
  scale_x_date(date_breaks = "2 year", date_labels = "%Y %b %d")+
  ylab("Euro Stoxx 50 price and profit")+
  xlab("Dates")+
  theme_light()+
  theme(axis.title=element_text(size=10,face="bold"),
        axis.text.x = element_text(angle=60, hjust=1),
        legend.position = 'none')
dev.off()

jpeg("./fig/rm_norm_profit_eurostoxx.jpg", units="in", width=7, height=7, res=300)
ggplot(dd_rm, aes(x=dates)) + 
  geom_point(aes(y = price, group=clust_1, color=clust_1), size=0.5) + 
  geom_bar(aes(y=normal_profit-profit, fill=clust_1),stat="identity")+  
  scale_fill_brewer(palette="Set2")+
  scale_colour_brewer(palette = "Set2")+
  scale_x_date(date_breaks = "2 year", date_labels = "%Y %b %d")+
  ylab("Euro Stoxx 50 price and profit")+
  xlab("Dates")+
  theme_light()+
  theme(axis.title=element_text(size=10,face="bold"),
        axis.text.x = element_text(angle=60, hjust=1),
        legend.position = 'none')
dev.off()
```